# Generated by Django 5.2.6 on 2025-09-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.FloatField(default=100.0),
        ),
    ]
